### PR TITLE
Boost is still a runtime dependency through triqs/utility/macros.hpp

### PR DESCRIPTION
**Pull request by Wentzell**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Wentzell** [comment]
@conda-forge-admin, please rerender

**Comment by Wentzell** [comment]
@conda-forge-admin, please rerender

**Comment by Wentzell** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
This is now building properly. The issue was the python28.yaml migration file.

**Comment by Wentzell** [comment]
@beckermr Thank you!

**Comment by Wentzell** [comment]
Looks like I am now back to the package conflicts I mentioned already on the conda forge gitter.

**Comment by beckermr** [comment]
Well at least it builds on the feedstock now. These conflicts are hard. You might try a tool called mamba. It does fast solves so you check the conflicts.

**Comment by Wentzell** [comment]
How is it that I never saw these conflicts in previous (successful) builds?
How should I read a conflict message such as

```
Package libcurl conflicts for:
libcurl==7.69.1=hc0b9707_0
cmake==3.17.0=hd28f656_0 -> libcurl[version='>=7.64.1,<8.0a0']
```

It is unclear to me what the problem is based on the message.

**Comment by beckermr** [comment]
I don't know either. Sorry! :(

**Comment by Wentzell** [comment]
@conda-forge-admin rerender

**Comment by Wentzell** [comment]
@conda-forge-admin rerender

**Comment by Wentzell** [comment]
@conda-forge-admin rerender

**Pull request merged**
