### PR TITLE
ENH add hdf5 1.10.6 by hand

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge/triqs This PR is needed to unblock the HDF5 1.10.6 migration. https://conda-forge.org/status/#hdf51106

I am not sure why the bot missed this one. cc @conda-forge/bot

**Comment by beckermr** [comment]
@conda-forge/triqs this is ready to merge!

**Comment by Wentzell** [comment]
Thank you @beckermr !

**Pull request merged**
